name: SEA-RAFT
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2024.12.31=hca03da5_0
  - libffi=3.4.4=hca03da5_1
  - ncurses=6.4=h313beb8_0
  - openssl=3.0.15=h80987f9_0
  - pip=24.2=py311hca03da5_0
  - python=3.11.11=hb885b13_0
  - readline=8.2=h1a28f6b_0
  - setuptools=75.1.0=py311hca03da5_0
  - sqlite=3.45.3=h80987f9_0
  - tk=8.6.14=h6ba3021_0
  - wheel=0.44.0=py311hca03da5_0
  - xz=5.4.6=h80987f9_1
  - zlib=1.2.13=h18a0788_1
  - pip:
      - aicsimageio==4.14.0
      - aiobotocore==2.5.4
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.11
      - aioitertools==0.12.0
      - aiosignal==1.3.2
      - anndata==0.11.3
      - annotated-types==0.7.0
      - array-api-compat==1.10.0
      - arrow==1.3.0
      - asciitree==0.3.3
      - attrs==24.3.0
      - botocore==1.31.17
      - certifi==2024.12.14
      - charset-normalizer==3.4.1
      - click==8.1.8
      - cloudpickle==3.1.0
      - contourpy==1.3.1
      - cycler==0.12.1
      - dask==2024.12.1
      - dicom2nifti==2.5.1
      - distributed==2024.12.1
      - dropbox==12.0.2
      - elementpath==4.7.0
      - et-xmlfile==2.0.0
      - fasteners==0.19
      - filelock==3.16.1
      - fonttools==4.55.3
      - frozenlist==1.5.0
      - fsspec==2023.6.0
      - git-filter-repo==2.47.0
      - h5py==3.12.1
      - huggingface-hub==0.27.1
      - idna==3.10
      - imagecodecs==2024.12.30
      - imageio==2.36.1
      - importlib-metadata==8.5.0
      - importlib-resources==6.5.2
      - jinja2==3.1.5
      - jmespath==1.0.1
      - kiwisolver==1.4.8
      - lazy-loader==0.4
      - llvmlite==0.43.0
      - locket==1.0.0
      - lxml==4.9.4
      - markupsafe==3.0.2
      - matplotlib==3.10.0
      - mdai==0.15.0
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.1.0
      - natsort==8.4.0
      - networkx==3.4.2
      - nibabel==5.3.2
      - numba==0.60.0
      - numcodecs==0.14.1
      - numpy==1.26.4
      - ome-types==0.5.3
      - ome-zarr==0.10.3
      - opencv-python==4.10.0.84
      - openpyxl==3.1.5
      - packaging==24.2
      - pandas==2.2.3
      - partd==1.4.2
      - pillow==10.4.0
      - ply==3.11
      - propcache==0.2.1
      - psutil==6.1.1
      - pyarrow==18.1.0
      - pydantic==2.10.5
      - pydantic-compat==0.1.2
      - pydantic-core==2.27.2
      - pydicom==2.4.4
      - pyparsing==3.2.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-gdcm==3.0.24.1
      - python-graphviz==0.20.3
      - pytz==2024.2
      - pyyaml==6.0.2
      - requests==2.32.3
      - resource-backed-dask-array==0.1.0
      - retrying==1.3.4
      - s3fs==2023.6.0
      - scikit-image==0.25.0
      - scip==0.1.12
      - scipy==1.15.1
      - six==1.17.0
      - sortedcontainers==2.4.0
      - stone==3.3.1
      - sympy==1.13.1
      - tblib==3.0.0
      - tifffile==2023.2.28
      - toolz==1.0.0
      - torch==2.5.1
      - torchaudio==2.5.1
      - torchvision==0.20.1
      - tornado==6.4.2
      - tqdm==4.67.1
      - types-python-dateutil==2.9.0.20241206
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - urllib3==1.26.20
      - wrapt==1.17.1
      - xarray==2025.1.1
      - xmlschema==3.4.3
      - xsdata==24.3.1
      - yarl==1.18.3
      - zarr==2.15.0
      - zict==3.0.0
      - zipp==3.21.0
prefix: /Users/Shreya1/anaconda3/envs/SEA-RAFT
